version: '2'

services:
  namenode:
    build: ../master_server_node
    image: nvent_hwx/master_server_node
    hostname: namenode
    container_name: namenode
    privileged: true
    dns: 8.8.8.8
    network_mode: "bridge"
    environment:
      - AMBARI_SERVER=namenode
      - BLUEPRINT_BASE=${BLUEPRINT_BASE}
    ports:
      - "8080:8080"
      - "3000:3000"
      - "8440:8440"
      - "8441:8441"
      - "50070:50070"
      - "8020:8020"
    volumes:
      - /data/namenode/hadoop:/hadoop
      - /usr/hdp
      - /var/log
      - /etc/hosts:/etc/hosts
  resourcemanager:
    build: ../agent_node
    image: nvent_hwx/agent_node
    hostname: resourcemanager
    container_name: resourcemanager
    privileged: true
    dns: 8.8.8.8
    network_mode: "bridge"
    environment:
      - AMBARI_SERVER=namenode
    links:
      - namenode:namenode
    ports:
      - "8088:8088"
      - "8032:8032"
      - "50060:50060"
      - "50090:50090"
      - "8081:8081"
      - "8030:8030"
      - "8050:8050"
      - "8025:8025"
      - "8141"
      - "8440"
      - "8441"
      - "19888:19888"
      - "45454"
      - "10020:10020"
      - "22"
    volumes:
      - /data/resourcemanager/hadoop:/hadoop
      - /usr/hdp
      - /var/log
      - /etc/hosts:/etc/hosts
  hiveserver:
    image: nvent_hwx/agent_node
    hostname: hiveserver
    container_name: hiveserver
    privileged: true
    dns: 8.8.8.8
    network_mode: "bridge"
    environment:
      - AMBARI_SERVER=namenode
    links:
      - namenode:namenode
    ports:
      - "11000:11000"
      - "2181"
      - "50111:50111"
      - "9083"
      - "10000"
      - "9999:9999"
      - "9933:9933"
      - "22"
      - "8440"
      - "8441"
    volumes:
      - /data/hiveserver/hadoop:/hadoop
      - /usr/hdp
      - /var/log
      - /etc/hosts:/etc/hosts
    depends_on:
      - resourcemanager
